### ISSUE TITLE
システムコールをwrapする

### ISSUE THREAD

**Issue by bayamasa** [42Student-July/minishell_submit_bayaki#20]
今だとdup2とかcloseはwrapしていないので、-1の戻り値を読み捨てている。
これを防ぎたいので、wrapper関数を作って対処したい。

**Comment by AkkyOrz** [comment]
`open` はwrapしないほうが良さそう
なぜなら、開けないというイベントも正常系に含まれている可能性があり、exit_status`に関わるから

**Comment by AkkyOrz** [comment]
- readline
- rl_clear_history
- rl_on_new_line
- rl_replace_line
- rl_redisplay
- add_history
- printf
- malloc
- free
- write
- access
- open
- read
- close
- fork
- wait
- waitpid
- wait3
- wait4
- signal
- sigaction
- sigemptyset
- sigaddset
- kill
- exit
- getcwd
- chdir
- stat
- lstat
- fstat
- unlink
- execve
- dup
- dup2
- pipe
- opendir
- readdir
- closedir
- strerror
- perror
- isatty
- ttyname
- ttyslot
- ioctl
- getenv
- tcsetattr
- tcgetattr
- tgetent
- tgetflag
- tgetnum
- tgetstr
- tgoto
- tputs
-
